# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20180413_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='approved',
            new_name='isModerated',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='response_wanted',
            new_name='responsesRequired',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='text',
            new_name='story',
        ),
    ]
