# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20180413_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='approved',
            new_name='isModerated',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='text',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='response',
            name='date',
        ),
    ]
