# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_response_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='story',
            new_name='storyId',
        ),
    ]
